<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class inventoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barang = [
            ['nama_barang' => 'Roti Bakar', 'id_kategori' => 1, 'lead_time' => 7, 'id_uom' => 12, 'stok' => 48],
            ['nama_barang' => 'Roti Jadul', 'id_kategori' => 1, 'lead_time' => 7, 'id_uom' => 12, 'stok' => 0],
            ['nama_barang' => 'Indomie Goreng', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 26],
            ['nama_barang' => 'Indomie Soto', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 53],
            ['nama_barang' => 'Indomie Ayam Bawang', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 42],
            ['nama_barang' => 'Telur', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 8],
            ['nama_barang' => 'Telur Ayam Kampung', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Cream Mocca', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Kentang Goreng', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 14],
            ['nama_barang' => 'SKM Coklat', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 6, 'stok' => 47.46],
            ['nama_barang' => 'Kornet', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 6, 'stok' => 2.26],
            ['nama_barang' => 'Kacang Sangrai', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Coklat Goldenfil', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Mentega', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 15],
            ['nama_barang' => 'Mayones', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Srikaya', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 1.95],
            ['nama_barang' => 'Meses | Garuda', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 18.42],
            ['nama_barang' => 'Keju', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 4.05],
            ['nama_barang' => 'Sirup | Bangau', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 2],
            ['nama_barang' => 'Beras', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 3],
            ['nama_barang' => 'Chia Seed | JUS KODE', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 1070],
            ['nama_barang' => 'Gula Cair 24 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 48],
            ['nama_barang' => 'Saus Sambal', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 5],
            ['nama_barang' => 'Air Botol 330 ML', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Kolang Kaling', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Jelly King Nata', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 9.51],
            ['nama_barang' => 'Nata De Coco', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 2],
            ['nama_barang' => 'NataKu 1 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0.96],
            ['nama_barang' => 'Madu Multifora', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 15.13],
            ['nama_barang' => 'Seblak Pack', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 7],
            ['nama_barang' => 'Bakso Aci Pack', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 24],
            ['nama_barang' => 'Susu UHT Diamond ( Chia seed )', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Susu UHT Ultra Milk 1000 ML', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Gula', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 80],
            ['nama_barang' => 'Gula Karung GMP 8 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Morin Topping Blueberry 310 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 3],
            ['nama_barang' => 'Morin Topping Blueberry 300 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0.54],
            ['nama_barang' => 'Morin Topping Strawberry 310 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Morin Topping Strawberry 300 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 2.06],
            ['nama_barang' => 'Singkong Keju Frozen 700 Gr', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 5.68],
            ['nama_barang' => 'Singkong Frozen', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Otak Otak Minaku 500 Gr', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Otak Otak Indomina 500 Gr', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 12.98],
            ['nama_barang' => 'Otak-Otak', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Skm Putih 488 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 6, 'stok' => 81.33],
            ['nama_barang' => 'SKM Putih', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 6, 'stok' => 0],
            ['nama_barang' => 'Karage', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Karage Perfectio 450 Gram', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Karage Perfectio 250 Gram', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Jelly Mutiara Super Aneka 1000 Gram', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Jelly Mutiara Super Aneka 250 Gram', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 1.72],
            ['nama_barang' => 'Matcha Bubuk 100 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Matcha Pure Nutrifarm 270 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Matcha Pure Bleuherbz 100 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Matcha Pure Cy Beverages 50 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Hydro Coco 1000 ML', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Hydro Coco 500 Ml', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Hydro Coco 330 ML', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 3],
            ['nama_barang' => 'Whipccream Richgold 907 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 2],
            ['nama_barang' => 'Whipccream Richgold 500 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Nori Gimbori Original MamaSuka 25 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 0],
            ['nama_barang' => 'Nori Gimbori Original MamaSuka 30 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 0],
            ['nama_barang' => 'Nori Gimbori Original MamaSuka 50 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Cocoa Powder Coklat 165 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 1.97],
            ['nama_barang' => 'Cocoa Powder Coklat 80 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Cocoa Powder Coklat 45 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Cocoa Powder Coklat 40 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Yoghurt Kin Slurp Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 18],
            ['nama_barang' => 'Yoghurt Cimory Slurp Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Blue Spirulina 50 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 1.9],
            ['nama_barang' => 'Blue Spirulina Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Sirup Marjan Mocca 460 Ml', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 0],
            ['nama_barang' => 'Sirup Bangau Moka 620 Ml', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 1.59],
            ['nama_barang' => 'Fish Roll Cedea 1 Kg', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Fish Roll Shifudo 500 Gr Isi 20 Pcs', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 7.5],
            ['nama_barang' => 'Mini Wonton Bumifood 500 Gr', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 1.6],
            ['nama_barang' => 'Mini Wonton Bumifood 200 Gr', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 10],
            ['nama_barang' => 'Saus Sambal Bangkok 50 Sachet 9 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 3.18],
            ['nama_barang' => 'Saus Sambal Bangkok 100 Sachet 9 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Aloe Vera Grape Low Sugar Wong Coco 280 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 10],
            ['nama_barang' => 'Selai Morin Kacang 2 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 1.98],
            ['nama_barang' => 'Stevia Tropicana Slim 2.2 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 24],
            ['nama_barang' => 'Mayones Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 22],
            ['nama_barang' => 'Chicken Katsu Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Caesim', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Wedang Uwuh', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 19],
            ['nama_barang' => 'Jahe', 'id_kategori' => 1, 'lead_time' => 1, 'id_uom' => 7, 'stok' => 0.13],
            ['nama_barang' => 'Cireng Rujak Original Brecxelle Isi 20 Pcs', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 13.5],
            ['nama_barang' => 'Piscok Brecxelle Isi 10 Pcs', 'id_kategori' => 1, 'lead_time' => 2, 'id_uom' => 10, 'stok' => 7.8],
            ['nama_barang' => 'Sari Jeruk Nipis Murni Nutripedia 500 Ml', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 5.27],
            ['nama_barang' => 'Cheese Roll 250 Gr Mey Mey Isi 20 Pcs', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Ice Cream Vanilla Diamond 8 Liter', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 3, 'stok' => 1.14],
            ['nama_barang' => 'Ice Cream Vanilla Aice 8 Liter', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 3, 'stok' => 0],
            ['nama_barang' => 'Nescafe Ice Roast 2 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 23],
            ['nama_barang' => 'Selasih No Brand 1 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0.95],
            ['nama_barang' => 'Saus Tomat Delmonte 24 Sachet', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 1.79],
            ['nama_barang' => 'Psyllium Husk Naturelife 200 Gr', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 15, 'stok' => 3],
            ['nama_barang' => 'Whey Protein Pack 1 Kg', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Jus Mata', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 6],
            ['nama_barang' => 'Jus Kolestrol', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Jus Jantung', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 36],
            ['nama_barang' => 'Jus Radang', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Jus Anti Kanker', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Jus Diabetes', 'id_kategori' => 1, 'lead_time' => 3, 'id_uom' => 10, 'stok' => 8],
            ['nama_barang' => 'Sedotan | JUS KODE', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 8.69],
            ['nama_barang' => 'Hot Cup Dan Tutup 240 ML', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 73],
            ['nama_barang' => 'Cup Besar (Plastik) | JUS KODE', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 635],
            ['nama_barang' => 'Cup Kecil (Plastik) | JUS KODE', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 480],
            ['nama_barang' => 'Alpukat (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0.93],
            ['nama_barang' => 'Blackberry (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 4.32],
            ['nama_barang' => 'Jambu (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Jeruk (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 7.56],
            ['nama_barang' => 'Kelapa Muda', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Kelapa Ijo', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Mangga (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Mangga Frozen (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 48.76],
            ['nama_barang' => 'Melon (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 4.28],
            ['nama_barang' => 'Naga (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Nangka (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Sirsak (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 21.6],
            ['nama_barang' => 'Pisang (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Strawberry (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 61.7],
            ['nama_barang' => 'Terong Belanda (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Tomat (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Wortel (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Pepaya (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Blueberry (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 27.5],
            ['nama_barang' => 'Nanas (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 2.34],
            ['nama_barang' => 'Markisa (Buah Utuh)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 4.9],
            ['nama_barang' => 'Pandan', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Alpukat (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 3.6],
            ['nama_barang' => 'Blackberry (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 0.5],
            ['nama_barang' => 'Jambu (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 10.84],
            ['nama_barang' => 'Jeruk (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 9, 'stok' => 0],
            ['nama_barang' => 'Kelapa (Air)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 9, 'stok' => 0],
            ['nama_barang' => 'Mangga (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Mangga Frozen (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 1.15],
            ['nama_barang' => 'Melon (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 3.06],
            ['nama_barang' => 'Naga (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 18.16],
            ['nama_barang' => 'Nangka (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Sirsak (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 0.8],
            ['nama_barang' => 'Pisang (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 4.52],
            ['nama_barang' => 'Strawberry (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 0.3],
            ['nama_barang' => 'Terong Belanda (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Tomat (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 1.84],
            ['nama_barang' => 'Wortel (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Pepaya (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Blueberry (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 0.9],
            ['nama_barang' => 'Nanas (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 2, 'id_uom' => 7, 'stok' => 2.2],
            ['nama_barang' => 'Markisa (Buah Prep)', 'id_kategori' => 3, 'lead_time' => 3, 'id_uom' => 7, 'stok' => 0.5],
            ['nama_barang' => 'Minyak', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 8, 'stok' => 8],
            ['nama_barang' => 'Es Batu', 'id_kategori' => 1, 'lead_time' => 1, 'id_uom' => 1, 'stok' => 0],
            ['nama_barang' => 'Garam', 'id_kategori' => 1, 'lead_time' => 1, 'id_uom' => 7, 'stok' => 3],
            ['nama_barang' => 'Bakmi Ayam Mentah', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Daging Ayam', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Minyak Bawang', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 0],
            ['nama_barang' => 'Bumbu Yamin Asin', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Bumbu Yamin Manis', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 5, 'stok' => 0],
            ['nama_barang' => 'Sambal Rawit Level', 'id_kategori' => 1, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Roll Plastic Sealing', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 13, 'stok' => 3],
            ['nama_barang' => 'Mika Besar', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 9],
            ['nama_barang' => 'Plastik Bawang | JUS KODE', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 5],
            ['nama_barang' => 'Plastik Logo TakeAway 24 | JUS KODE', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 7, 'stok' => 24],
            ['nama_barang' => 'Plastik Wrap Makanan 40 Cm', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Sendok Garpu Plastik 2 In 1', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 86],
            ['nama_barang' => 'Plastik Sampah', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 29],
            ['nama_barang' => 'Thin Wall 750 ML', 'id_kategori' => 2, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 336],
            ['nama_barang' => 'Sabun Kaca / Untuk Semprot Kaca', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 4, 'stok' => 0],
            ['nama_barang' => 'Kawat Besi', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Karbol', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 4, 'stok' => 3],
            ['nama_barang' => 'Sabun Cuci Piring', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 4, 'stok' => 0],
            ['nama_barang' => 'Sabun Cuci Tangan', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 4, 'stok' => 3],
            ['nama_barang' => 'Hogasan', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 3],
            ['nama_barang' => 'Baygon', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 1],
            ['nama_barang' => 'Vixal', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Hairnet', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 3, 'stok' => 0],
            ['nama_barang' => 'Sarung Tangan / HandGlove', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 3, 'stok' => 1],
            ['nama_barang' => 'Masker', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 3, 'stok' => 10],
            ['nama_barang' => 'Tissue | See U', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 89],
            ['nama_barang' => 'Pewangi Ruangan Refill', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 6, 'stok' => 1],
            ['nama_barang' => 'Kamper (Untuk Kamar Mandi)', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 3],
            ['nama_barang' => 'Keset Karpet PVC', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 13, 'stok' => 0],
            ['nama_barang' => 'Sabut Spons', 'id_kategori' => 4, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 3],
            ['nama_barang' => 'Botol Kosong 350 ML (Untuk Event/Pesanan)', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 2, 'stok' => 100],
            ['nama_barang' => 'Kertas Thermal | JUS KODE', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 13, 'stok' => 55],
            ['nama_barang' => 'Pulpen', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Selotip 24 MM / 1 Inch (Untuk Kasir)', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 11],
            ['nama_barang' => 'Kertas Nasi', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Gas 12 Kg Movement', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Gas 5.5 Kg Movement', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Gas 3 Kg Movement', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Food Wrap Grib 18x18 Isi 50 Lembar', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Food Wrap Grib 18x18 Isi 500 Lembar', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Food Wrap Grib 30x30 Isi 100 Lembar', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Food Wrap Grib 30x30 Isi 200 Lembar', 'id_kategori' => 5, 'lead_time' => 4, 'id_uom' => 10, 'stok' => 0],
            ['nama_barang' => 'Kanebo', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Golok', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Gelas Takar 500 ML', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Gelas Takar 2000 ML', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Topi Staff', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 11],
            ['nama_barang' => 'Perasan Jeruk', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Tray Timbang Buah / Keranjang Buah', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 20],
            ['nama_barang' => 'Sapu Lantai', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Pel Lantai', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Sapu Lidi', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Cup Plastik (Untuk Infuse Water)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 0],
            ['nama_barang' => 'Gelas Kaca Besar', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 55],
            ['nama_barang' => 'Gelas Kaca Kecil', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 38],
            ['nama_barang' => 'Pisau Besar', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Mangkok Indomie', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 20],
            ['nama_barang' => 'Mangkok Karage', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 20],
            ['nama_barang' => 'Piring (Roti Bakar)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 22],
            ['nama_barang' => 'Tempat Kondimen Roti', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 20],
            ['nama_barang' => 'Sendok Stainlis', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 24],
            ['nama_barang' => 'Garpu Stainlis', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 63],
            ['nama_barang' => 'Talenan Kayu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Tempat Kondimen Buah Bar Plastik', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 6],
            ['nama_barang' => 'Blender', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 8],
            ['nama_barang' => 'Timbangan Digital Kapasitas 150 Kg', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Timbangan Digital 5 Kg', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Freezer 2 Pintu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Chiller 3 Pintu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Meja Kaca', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 30],
            ['nama_barang' => 'Meja Dine In Kayu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Bangku Besi', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 30],
            ['nama_barang' => 'Bangku Anyam', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 5],
            ['nama_barang' => 'Kipas Dinding', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 12],
            ['nama_barang' => 'Xhoust', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 12],
            ['nama_barang' => 'Sepatula', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Scoope Besar (Lama)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Scoope Kecil (Lama)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Scoope 1/1 (Baru)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Scoope 1/2 (Baru)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 5],
            ['nama_barang' => 'Scoope 1/3 (Baru)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Teko Plastik', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Container / Kontainer 25 Liter', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 5],
            ['nama_barang' => 'Talenan Plastik', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Palu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Dudukan Kompor', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Panci Mie', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Dispenser Selotip (Untuk Kasir)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Filter RO', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Jigger', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 14],
            ['nama_barang' => 'AC 2 PK', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Tempat Sampah Customer', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 7],
            ['nama_barang' => 'Pealer / Pengupas / Kupas Buah', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Kabel Roll', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Hp Outlet', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Hp Outlet Tab', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Tray Stainliss', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 3],
            ['nama_barang' => 'Lap Micro Kuning / Abu', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 20],
            ['nama_barang' => 'Kepala Regulator Gas', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Apron / Celemek', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 11],
            ['nama_barang' => 'Wipper Kaca', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Wipper Lantai / Tarikan Air', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Centong Gula', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Cash Drawer / Mesin Kasir', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Gunting', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Kamera CCTV', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 12],
            ['nama_barang' => 'HT / Handy talkie / Walkie Talkie / Walki', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Meja Kayu Prep', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 5],
            ['nama_barang' => 'Wajan Panggang Roti Bakar', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Mesin Es Serut', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Kompor 2 Tungku', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Parutan Keju', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Piller (Pengupas Buah)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Tutup Gelas', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Alat Pengasah Pisau', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Panci Gula', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 3],
            ['nama_barang' => 'Teplon Wajan Telur', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Papan No Antrian', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Mesin Sealer', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Mangkok Telur Kampung', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 15],
            ['nama_barang' => 'Papan Tulis Kapur', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Panci Diameter 36 Cm (Telur Ayam Kampung)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Rice Cooker  1.85 Liter', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Gelas Takar Kaca', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Toples Kaca Besar', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Toples Kaca Kecil', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Mixer Kecil (Frother)', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Saringan Jambu 10 Cm Diameter', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 4],
            ['nama_barang' => 'Saringan Bakmi Ayam', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Box Souce/Sambal 14"', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
            ['nama_barang' => 'Food Pan 1/3', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 15],
            ['nama_barang' => 'Dispenser Termos Air 10 L | Royalstar', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Container Whey Protein 1200 ML', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 11, 'stok' => 1],
            ['nama_barang' => 'Scoop Whey Protein 30 Gr', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'Pengki Kebersihan', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 1],
            ['nama_barang' => 'Piring Saji Grid Fast Food R Plusware', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 10],
            ['nama_barang' => 'Piring Saji Grid Fast Food L Plusware', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 10],
            ['nama_barang' => 'Scoop Ice Cream', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 2],
            ['nama_barang' => 'AC Outdoor', 'id_kategori' => 6, 'lead_time' => 4, 'id_uom' => 14, 'stok' => 0],
        ];

        DB::table('inventori')->insert($barang);
    }
}
